# .github/actions/build-engine/action.yml
name: ""
description: "Build the engine with a specific gclient setup and config name"
inputs:
  gclient:
    description: "gclient name"
    required: false
    default: ""
  config_name:
    description: "name of a valid et config"
    required: false
    default: ""
  engine_version:
    description: "the engine version for the output assets"
    required: false
    default: ""
  gcp_credentials:
    description: "the engine version for the output assets"
    required: false
    default: ""
runs:
  using: "composite"
  defaults:
    run:
      shell: bash
  steps:
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Setup gcloud
      env:
        GCP_CREDENTIALS: ${{ inputs.gcp_credentials }}
      run: |
        echo "$GCP_CREDENTIALS"  | base64 -d  > "$HOME"/gcloud.json
        gcloud auth activate-service-account --key-file="$HOME"/gcloud.json

    - name: Free disk space
      if: contains(matrix.os, 'ubuntu')
      run: curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash

    - name: Check out the repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up depot_tools / gclient
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
        # Append depot_tools to the PATH for subsequent steps
        echo "$HOME/depot_tools" >> $GITHUB_PATH

    - name: Copy gclient file
      run: |
        # Use custom gclient to trim size
        cp engine/scripts/${{ inputs.gclient }}.gclient .gclient

    - name: Gclient sync
      run: gclient sync -D

    - name: Fetch engine dependencies
      run: |
        cd engine/src
        ./flutter/bin/et fetch

    - name: Build Engine
      run: |
        echo "Running et config: ${{ inputs.config_name }}"
        cd engine/src
        ./flutter/bin/et build --config ${{ inputs.config_name }}

    - name: Copy Zip Archives
      if: ${{ hashFiles(format('engine/src/out/{0}/zip_archives/**', inputs.config_name))!= ''  && contains(inputs.config_name, 'test') == false}}
      run: |
        cd engine/src
        echo "copying output to /build_outputs/flutter/engine/<engine-revision>/<platform>/<artifact-name>"
        gcloud storage cp --recursive out/${{ inputs.config_name }}/zip_archives/* gs://flutter-builds/flutter_infra_release/flutter/engine/${{ inputs.engine_version }}/


    - name: Copy Engine Outputs
      if: ${{ hashFiles(format('engine/src/out/{0}/zip_archives/**', inputs.config_name)) == '' && contains(inputs.config_name, 'test') == false }}
      run: |
        cd engine/src
        echo "copying output to /build_outputs/flutter/engine/<engine-revision>/<platform>/<artifact-name>"
        tar c out/${{ inputs.config_name }} | gzip > out/${{ inputs.config_name }}.tar.gz
        gcloud storage cp --recursive out/${{ inputs.config_name }}.tar.gz gs://flutter-builds/flutter_infra_release/flutter/engine/${{ inputs.engine_version }}/${{ inputs.config_name }}.tar.gz
