name: Build Flutter Engine with Engine Tool (Matrix)

on:
  push:
    branches: [ "main", "stable", "beta", "engine-builds" ]
  pull_request:
    branches: [ "main", "stable", "beta", "engine-builds" ]
env:
  # don't try to install google's internal copy of visual studio
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0

jobs:
  build-engine:
    # We'll run on whatever OS the matrix entry specifies.
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      max-parallel: 10
      matrix:
        include:

          - name: linux host release
            os: depot-ubuntu-22.04-2
            config_name: ci/host_release_desktop

          - name: linux host debug
            config_name: ci/host_debug_desktop
            os: depot-ubuntu-22.04-2

          #- name: linux host release
          #  os: depot-ubuntu-22.04-2
          #  config_name: host_profile

          #- name: linux host release
          #  os: depot-ubuntu-22.04-2
          #  config_name: host_profile_arm64

          #- name: linux host release
          #  os: depot-ubuntu-22.04-2
          #  config_name: host_release_arm64

          - name: linux host debug arm64 tests
            os: depot-ubuntu-22.04-2
            config_name: ci/host_debug_arm64_tests

          - name: linux host debug clang tidy
            os: depot-ubuntu-22.04-2
            config_name: ci/host_debug_clang_tidy

          - name: linux host debug test
            os: depot-ubuntu-22.04-2
            config_name: ci/host_debug_test

          - name: linux host debug ddm
            os: depot-ubuntu-22.04-2
            config_name: ci/host_debug_ddm

          - name: linux host debug no prebuilt dart sdk
            os: depot-ubuntu-22.04-2
            config_name: ci/host_debug_no_prebuilt_dart_sdk

          - name: linux host debug unopt
            os: depot-ubuntu-22.04-2
            config_name: ci/host_debug_unopt

          - name: linux host debug unopt impeller tests
            os: depot-ubuntu-22.04-2
            config_name: ci/host_debug_unopt_impeller_tests
          - name: linux host profile desktop
            os: depot-ubuntu-22.04-2
            config_name: ci/host_profile_desktop
          - name: linux host profile test
            os: depot-ubuntu-22.04-2
            config_name: ci/host_profile_test
          - name: linux host release test
            os: depot-ubuntu-22.04-2
            config_name: ci/host_release_test
          - name: linux debug arm64
            os: depot-ubuntu-22.04-2
            config_name: ci/linux_debug_arm64

          - name: linux profile arm64
            os: depot-ubuntu-22.04-2
            config_name: ci/linux_profile_arm64
          - name: linux release arm64
            os: depot-ubuntu-22.04-2
            config_name: ci/linux_release_arm64

          - name: web_tests/test_bundles/dart2js-canvaskit-canvaskit
            os: depot-ubuntu-22.04-2
            config_name: web_tests/test_bundles/dart2js-canvaskit-canvaskit
          - name: web_tests/test_bundles/dart2js-canvaskit-engine
            os: depot-ubuntu-22.04-2
            config_name: web_tests/test_bundles/dart2js-canvaskit-engine
          - name: web_tests/test_bundles/dart2js-canvaskit-ui
            os: depot-ubuntu-22.04-2
            config_name: web_tests/test_bundles/dart2js-canvaskit-ui
          - name: web_tests/test_bundles/dart2wasm-canvaskit-engine
            os: depot-ubuntu-22.04-2
            config_name: web_tests/test_bundles/dart2wasm-canvaskit-engine
          - name: web_tests/test_bundles/dart2wasm-skwasm-ui
            os: depot-ubuntu-22.04-2
            config_name: web_tests/test_bundles/dart2wasm-skwasm-ui
          - name: web_tests/test_bundles/fallbacks
            os: depot-ubuntu-22.04-2
            config_name: web_tests/test_bundles/fallbacks


          #- name: linux host profile
          #  os: depot-ubuntu-22.04-2
          #  config_name: ci/host_profile


          - name: linux host release
            os: depot-ubuntu-22.04-2
            config_name: ci/host_release

          - name: linux host debug
            config_name: ci/host_debug
            os: depot-ubuntu-22.04-2

          - name: linux wasm release (web)
            config_name: wasm_release
            os: depot-ubuntu-22.04-2

          - name: linux wasm debug (web)
            config_name: wasm_debug_unopt
            os: depot-ubuntu-22.04-2

          - name: android debug
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug

          - name: android debug arm64
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_arm64

          - name: android debug arm64 clang tidy
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_arm64_clang_tidy

          - name: android debug arm64 ddm
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_arm64_ddm

          - name: android debug arm64 validation layers
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_arm64_validation_layers

          - name: android debug test
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_test

          - name: android debug unopt
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_unopt

          - name: android debug x64
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_x64

          - name: android debug x86
            os: depot-ubuntu-22.04-2
            config_name: ci/android_debug_x86

          - name: android embedder debug unopt
            os: depot-ubuntu-22.04-2
            config_name: ci/android_embedder_debug_unopt

          - name: android emulator debug x64
            os: depot-ubuntu-22.04-2
            config_name: ci/android_emulator_debug_x64

          - name: android emulator debug x86
            os: depot-ubuntu-22.04-2
            config_name: ci/android_emulator_debug_x86

          - name: android profile
            os: depot-ubuntu-22.04-2
            config_name: ci/android_profile

          - name: android profile arm64
            os: depot-ubuntu-22.04-2
            config_name: ci/android_profile_arm64

          - name: android profile x64
            os: depot-ubuntu-22.04-2
            config_name: ci/android_profile_x64

          - name: android release
            os: depot-ubuntu-22.04-2
            config_name:  ci/android_release

          - name: android release arm64
            os: depot-ubuntu-22.04-2
            config_name: ci/android_release_arm64

          - name: android release arm64 ddm
            os: depot-ubuntu-22.04-2
            config_name:  ci/android_release_arm64_ddm

          - name: android release x64
            os: depot-ubuntu-22.04-2
            config_name: ci/android_release_x64



         # ------------------------- MAC BUILDS -------------------------

          - name: mac debug arm64
            os: depot-macos-latest
            config_name: ci/mac_debug_arm64

          - name: mac debug framework arm64
            os: depot-macos-latest
            config_name: ci/mac_debug_framework_arm64

          - name: mac debug gen snapshot arm64
            os: depot-macos-latest
            config_name: ci/mac_debug_gen_snapshot_arm64

          - name: mac profile arm64
            os: depot-macos-latest
            config_name: ci/mac_profile_arm64

          - name: mac profile frmaoek arm64
            os: depot-macos-latest
            config_name: ci/mac_profile_framework_arm64

          - name: mac profile gen snapshot arm64
            os: depot-macos-latest
            config_name: ci/mac_profile_gen_snapshot_arm64

          - name: mac release arm64
            os: depot-macos-latest
            config_name: ci/mac_release_arm64

          - name: mac release arm64 tests
            os: depot-macos-latest
            config_name: ci/mac_release_arm64_tests

          - name: mac framework arm64
            os: depot-macos-latest
            config_name: ci/mac_release_framework_arm64

          - name: mac mac release gen snapshot arm64
            os: depot-macos-latest
            config_name: ci/mac_release_gen_snapshot_arm64

          - name: mac host debug arm64 tests
            os: depot-macos-latest
            config_name: ci/host_debug_arm64_tests

          - name: mac host debug clang tidy
            os: depot-macos-latest
            config_name: ci/host_debug_clang_tidy

          - name: mac host debug framework
            os: depot-macos-latest
            config_name:  ci/host_debug_framework

          - name: mac host debug den snapshot
            os: depot-macos-latest
            config_name: ci/host_debug_gen_snapshot

          - name: mac host debug unopt arm64
            os: depot-macos-latest
            config_name: ci/host_debug_unopt_arm64

          - name: mac host profile arm64 tests
            os: depot-macos-latest
            config_name: ci/host_profile_arm64_tests

          - name: mac host profile framework
            os: depot-macos-latest
            config_name: ci/host_profile_framework

          - name: mac host profile gen snapshot
            os: depot-macos-latest
            config_name: ci/host_profile_gen_snapshot

          - name: mac host release arm64 tests
            os: depot-macos-latest
            config_name: ci/host_release_arm64_tests

          - name: mac host release framework
            os: depot-macos-latest
            config_name: ci/host_release_framework

          - name: mac host release gen snapshot
            os: depot-macos-latest
            config_name: ci/host_release_gen_snapshot

          - name: mac host profile
            os: depot-macos-latest
            config_name: ci/host_profile

          #- name: mac host profile
          #  os: depot-macos-latest
          #  config_name: host_profile
          #- name: mac host profile arm64
          #  os: depot-macos-latest
          #  config_name: host_profile_arm64
          #- name: mac host arm64
          #  os: depot-macos-latest
          #  config_name: host_release_arm64

          - name: mac host release
            os: depot-macos-latest
            config_name: ci/host_release

          - name: mac host debug
            config_name: ci/host_debug
            os: depot-macos-latest

          - name: mac release framework
            config_name: ci/host_release_framework
            os: depot-macos-latest

          - name: mac debug framework
            config_name: ci/host_debug_framework
            os: depot-macos-latest

          - name: ios debug
            config_name: ci/ios_debug
            os: depot-macos-latest

          - name: ios debug sim
            config_name: ci/ios_debug_sim
            os: depot-macos-latest

          - name: ios debug sim arm64
            config_name: ci/ios_debug_sim_arm64
            os: depot-macos-latest

          - name: ios profile
            config_name: ci/ios_profile
            os: depot-macos-latest

          - name: ios release
            config_name: ci/ios_release
            os: depot-macos-latest

          - name: ios debug extension safe
            config_name: ci/ios_debug_extension_safe
            os: depot-macos-latest

          - name: ios debug sim arm64 extension safe
            config_name: ci/ios_debug_sim_arm64_extension_safe
            os: depot-macos-latest

          - name: ios debug sim extension safe
            config_name: ci/ios_debug_sim_extension_safe
            os: depot-macos-latest

          - name: ios debug unopt sim arm64 extension safe
            config_name: ci/ios_debug_unopt_sim_arm64_extension_safe
            os: depot-macos-latest

          - name: ios profile extension safe
            config_name: ci/ios_profile_extension_safe
            os: depot-macos-latest

          - name: ios release extension safe
            config_name: ci/ios_release_extension_safe
            os: depot-macos-latest

          # ------------------------- WINDOWS BUILDS -------------------------

          # Engine tool doesn't currently support windows
          #- name: Windows host release
          #  config_name: host_release
          #  os: windows-latest

    steps:
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Setup gcloud
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
        run: |
          echo "$GCP_CREDENTIALS"  | base64 -d  > "$HOME"/gcloud.json
          gcloud auth activate-service-account --key-file="$HOME"/gcloud.json

      - name: Free disk space
        if: contains(matrix.os, 'ubuntu')
        run: curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash

      - name: Check out the repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies (Example for Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            clang \
            cmake \
            ninja-build \
            unzip \
            zip \
            xz-utils \
            libgtk-3-dev \
            libglu-dev

      - name: Install Dependencies (Example for macOS)
        if: contains(matrix.os, 'macos')
        run: |
          brew update
          brew install \
            cmake \
            ninja

      - name: Install Dependencies (Example for Windows)
        if: contains(matrix.os, 'windows')
        run: |
          choco install -y -v \
            cmake \
            ninja

      - name: Set up depot_tools / gclient
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          # Append depot_tools to the PATH for subsequent steps
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      - name: gclient sync web_tests
        if: contains(matrix.os, 'ubuntu') && contains(matrix.config_name, 'web_tests')
        run: |
          # Use custom gclient to trim size
          cp engine/scripts/slim-linux-web.gclient .gclient
          gclient sync -D

      - name: gclient sync wasm
        if: contains(matrix.os, 'ubuntu') && contains(matrix.config_name, 'wasm')
        run: |
          # Use custom gclient to trim size
          cp engine/scripts/slim-linux-web.gclient .gclient
          gclient sync -D

      - name: gclient sync android
        if: contains(matrix.os, 'ubuntu') && contains(matrix.config_name, 'android')
        run: |
          engine/src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64

          # Use custom gclient to trim size
          cp engine/scripts/slim-linux-android.gclient .gclient
          gclient sync -D

      - name: gclient sync linux
        if: contains(matrix.os, 'ubuntu') && (contains(matrix.config_name, 'linux') || contains(matrix.config_name, 'host'))
        run: |
          # Use custom gclient to trim size
          cp engine/scripts/slim-linux-desktop.gclient .gclient
          gclient sync -D

      - name: gclient sync macos
        if: contains(matrix.os, 'macos')
        run: |
          # Use custom gclient to trim size
          cp engine/scripts/slim-mac.gclient .gclient
          gclient sync -D

      - name: gclient sync windows
        if: contains(matrix.os, 'windows')
        run: |
          # Use custom gclient to trim size
          cp engine/scripts/slim-windows.gclient .gclient
          gclient sync -D

      - name: Fetch engine dependencies
        run: |
          cd engine/src
          ./flutter/bin/et fetch

      - name: Build Engine
        run: |
          echo "Building config: ${{ matrix.config_name }}"
          cd engine/src
          ./flutter/bin/et build --config ${{ matrix.config_name }}

      - name: Copy Zip Archives
        if: ${{ hashFiles(format('engine/src/out/{0}/zip_archives/**', matrix.config_name))!= ''}}
        run: |
          cd engine/src
          echo "copying output to /build_outputs/flutter/engine/<engine-revision>/<platform>/<artifact-name>"

          gcloud storage cp --recursive out/${{ matrix.config_name }}/zip_archives/* gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/


      - name: Copy Engine Outputs
        if: ${{ hashFiles(format('engine/src/out/{0}/zip_archives/**', matrix.config_name)) == '' }}
        run: |
          cd engine/src
          echo "copying output to /build_outputs/flutter/engine/<engine-revision>/<platform>/<artifact-name>"
          tar c out/${{ matrix.config_name }} | gzip > out/${{ matrix.config_name }}.tar.gz
          gcloud storage cp --recursive out/${{ matrix.config_name }}.tar.gz gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/${{ matrix.config_name }}.tar.gz


  build-release:
    needs: build-engine
    runs-on: depot-ubuntu-22.04-2
    defaults:
      run:
        shell: bash

    steps:
      - name: Free disk space
        if: contains(matrix.os, 'ubuntu')
        run: curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Setup gcloud
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
        run: |
          echo "$GCP_CREDENTIALS"  | base64 -d  > "$HOME"/gcloud.json
          gcloud auth activate-service-account --key-file="$HOME"/gcloud.json

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: build ios release
        run: |

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_profile.tar.gz' .
          tar -xzf ios_profile.tar.gz
          rm ios_profile.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_debug.tar.gz' .
          tar -xzf ios_debug.tar.gz
          rm ios_debug.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_release.tar.gz' .
          tar -xzf ios_release.tar.gz
          rm ios_release.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_debug_sim.tar.gz' .
          tar -xzf ios_debug_sim.tar.gz
          rm ios_debug_sim.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_debug_sim_arm64.tar.gz' .
          tar -xzf ios_debug_sim_arm64.tar.gz
          rm ios_debug_sim_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_release_extension_safe.tar.gz' .
          tar -xzf ios_release_extension_safe.tar.gz
          rm ios_release_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_debug_extension_safe.tar.gz' .
          tar -xzf ios_debug_extension_safe.tar.gz
          rm ios_debug_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_debug_sim_arm64_extension_safe.tar.gz' .
          tar -xzf ios_debug_sim_arm64_extension_safe.tar.gz
          rm  ios_debug_sim_arm64_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_debug_unopt_sim_arm64_extension_safe.tar.gz' .
          tar -xzf ios_debug_unopt_sim_arm64_extension_safe.tar.gz
          rm ios_debug_unopt_sim_arm64_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_debug_sim_extension_safe.tar.gz' .
          tar -xzf ios_debug_sim_extension_safe.tar.gz
          rm ios_debug_sim_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_profile_extension_safe.tar.gz' .
          tar -xzf ios_profile_extension_safe.tar.gz
          rm ios_profile_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ci/ios_release_extension_safe.tar.gz' .
          tar -xzf ios_release_extension_safe.tar.gz
          rm ios_release_extension_safe.tar.gz


          python3 engine/src/flutter/sky/tools/create_ios_framework.py \
          --dst out/ios \
          --arm64-out-dir ios_debug \
          --simulator-x64-out-dir ios_debug_sim \
          --simulator-arm64-out-dir ios_debug_sim_arm64 \
          --dsym \
          --strip

          python3 engine/src/flutter/sky/tools/create_ios_framework.py \
          --dst out/ios_release \
          --arm64-out-dir ios_release \
          --simulator-x64-out-dir ios_debug_sim \
          --simulator-arm64-out-dir ios_debug_sim_arm64 \
          --dsym \
          --strip \

          python3 engine/src/flutter/sky/tools/create_ios_framework.py \
          --dst out/ios_profile \
          --arm64-out-dir ios_profile \
          --simulator-x64-out-dir ios_debug_sim \
          --simulator-arm64-out-dir ios_debug_sim_arm64 \
          --dsym \
          --strip \

          gcloud storage cp --recursive out/ios/ gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ios/
          gcloud storage cp --recursive out/ios_release/ gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ios_release/
          gcloud storage cp --recursive out/ios_profile/ gs://flutter-builds/flutter_infra_release/flutter/engine/${{ github.sha }}/ios_profile/

